# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: driver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64river.proto\x12\rdriverpackage\"3\n\x04\x44\x61ta\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\r\n\x05ports\x18\x02 \x01(\t\x12\t\n\x01m\x18\x03 \x01(\x05\"#\n\x06Status\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\x07\n\x05\x65mpty2=\n\x06\x44river\x12\x33\n\x05Start\x12\x13.driverpackage.Data\x1a\x15.driverpackage.Statusb\x06proto3')



_DATA = DESCRIPTOR.message_types_by_name['Data']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
_EMPTY = DESCRIPTOR.message_types_by_name['empty']
Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driverpackage.Data)
  })
_sym_db.RegisterMessage(Data)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driverpackage.Status)
  })
_sym_db.RegisterMessage(Status)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'driver_pb2'
  # @@protoc_insertion_point(class_scope:driverpackage.empty)
  })
_sym_db.RegisterMessage(empty)

_DRIVER = DESCRIPTOR.services_by_name['Driver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATA._serialized_start=31
  _DATA._serialized_end=82
  _STATUS._serialized_start=84
  _STATUS._serialized_end=119
  _EMPTY._serialized_start=121
  _EMPTY._serialized_end=128
  _DRIVER._serialized_start=130
  _DRIVER._serialized_end=191
# @@protoc_insertion_point(module_scope)
