# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import worker_pb2 as worker__pb2


class WorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetDriverPort = channel.unary_unary(
                '/workerpackage.Worker/SetDriverPort',
                request_serializer=worker__pb2.DriverPort.SerializeToString,
                response_deserializer=worker__pb2.Status.FromString,
                )
        self.Map = channel.unary_unary(
                '/workerpackage.Worker/Map',
                request_serializer=worker__pb2.MapInput.SerializeToString,
                response_deserializer=worker__pb2.Status.FromString,
                )
        self.Reduce = channel.unary_unary(
                '/workerpackage.Worker/Reduce',
                request_serializer=worker__pb2.ReduceId.SerializeToString,
                response_deserializer=worker__pb2.Status.FromString,
                )
        self.Terminate = channel.unary_unary(
                '/workerpackage.Worker/Terminate',
                request_serializer=worker__pb2.Empty.SerializeToString,
                response_deserializer=worker__pb2.Status.FromString,
                )


class WorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetDriverPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Map(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reduce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetDriverPort': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDriverPort,
                    request_deserializer=worker__pb2.DriverPort.FromString,
                    response_serializer=worker__pb2.Status.SerializeToString,
            ),
            'Map': grpc.unary_unary_rpc_method_handler(
                    servicer.Map,
                    request_deserializer=worker__pb2.MapInput.FromString,
                    response_serializer=worker__pb2.Status.SerializeToString,
            ),
            'Reduce': grpc.unary_unary_rpc_method_handler(
                    servicer.Reduce,
                    request_deserializer=worker__pb2.ReduceId.FromString,
                    response_serializer=worker__pb2.Status.SerializeToString,
            ),
            'Terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Terminate,
                    request_deserializer=worker__pb2.Empty.FromString,
                    response_serializer=worker__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workerpackage.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetDriverPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/workerpackage.Worker/SetDriverPort',
            worker__pb2.DriverPort.SerializeToString,
            worker__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Map(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/workerpackage.Worker/Map',
            worker__pb2.MapInput.SerializeToString,
            worker__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/workerpackage.Worker/Reduce',
            worker__pb2.ReduceId.SerializeToString,
            worker__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/workerpackage.Worker/Terminate',
            worker__pb2.Empty.SerializeToString,
            worker__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
